Added includedir

diff --git a/mkrootfs.sh.in b/mkrootfs.sh.in
--- a/mkrootfs.sh.in
+++ b/mkrootfs.sh.in
@@ -195,7 +195,7 @@ info_msg "Setting the default root password ('voidlinux')"
 if [ ! -f "$ROOTFS/etc/shadow" ] ; then
     run_cmd_chroot "$ROOTFS" pwconv
 fi
-echo root:voidlinux | run_cmd_chroot "$ROOTFS" "chpasswd -c SHA512" || die "Could not set default credentials"
+echo root:lazylinux | run_cmd_chroot "$ROOTFS" "chpasswd -c SHA512" || die "Could not set default credentials"
 rm -f "$ROOTFS/etc/.pwd.lock"
 
 # At this point we're done running things in the chroot and we can
